---
kind: pipeline
type: docker
name: default

steps:

- name: createimage
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - ls -l ./
  - ls -l /var/run/
  - docker build -t m5_buildroot .
  - chmod -R o+rw ./

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./dl

- name: bootstrap
  image: m5_buildroot
  pull: if-not-exists
  commands:
  - make bootstrap

- name: download
  image: m5_buildroot
  pull: if-not-exists
  commands:
  - make buildroot_dl

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./dl

- name: main
  image: m5_buildroot
  pull: if-not-exists
  commands:
  - make

volumes:
  - name: cache
    host: 
      path: /tmp/m5buildroot_cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock

...
